CREATE TABLE USERS (
    UserID INT NOT NULL AUTO_INCREMENT,
    UserName VARCHAR(255) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE,
    PRIMARY KEY (UserID)
);

CREATE TABLE SITES (
    UrlShort VARCHAR(15) NOT NULL,
    FullUrl VARCHAR(255) NOT NULL,
    UserID INT NOT NULL,
    PRIMARY KEY (UrlShort),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
        ON DELETE CASCADE
);

CREATE TABLE ACCESS (
    AccessID INT NOT NULL AUTO_INCREMENT,
    UrlShort VARCHAR(15) NOT NULL,
    AccessDateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IPAddress VARCHAR(45),
    PRIMARY KEY (AccessID),
    FOREIGN KEY (UrlShort) REFERENCES SITES(UrlShort)
        ON DELETE CASCADE
);
